CREATE TABLE ITEM
(
    ITEM_ID     NUMERIC      NOT NULL,
    NAME        VARCHAR(255) NOT NULL,
    DESCRIPTION VARCHAR(255) NOT NULL,
    PRICE       NUMERIC      NOT NULL,
    AMOUNT      NUMERIC      NOT NULL,
    CONSTRAINT PK_ITEM_ID primary key (ITEM_ID)
);
CREATE SEQUENCE ITEM_SEQ START WITH 1 INCREMENT BY 1;

CREATE TABLE CUSTOMER
(
    CUSTOMER_ID NUMERIC      NOT NULL,
    FIRST_NAME  VARCHAR(255) NOT NULL,
    LAST_NAME   VARCHAR(255) NOT NULL,
    EMAIL       VARCHAR(255) NOT NULL,
    PHONENUMBER VARCHAR(255) NOT NULL,
    ADDRESS     VARCHAR(255) NOT NULL,
    CONSTRAINT PK_CUSTOMER_ID PRIMARY KEY (CUSTOMER_ID)
);
CREATE SEQUENCE CUSTOMER_SEQ START WITH 1 INCREMENT BY 1;

INSERT INTO ITEM (ITEM_ID,NAME,DESCRIPTION,PRICE,AMOUNT)
VALUES(nextVal('item_seq'),'BANANA', 'curvy yellow thing', 1,100);
INSERT INTO CUSTOMER( CUSTOMER_ID,FIRST_NAME, LAST_NAME, EMAIL, PHONENUMBER, ADDRESS)
VALUES (nextVal('customer_seq'),'Rinaldo','Menichetti','rinaldo@mail.com','0498130333','my address');