CREATE TABLE ORDER_HEADER
(
    ORDER_HEADER_ID    NUMERIC,
    FK_CUSTOMER_ID NUMERIC,
    TOTAL_PRICE NUMERIC,
    CONSTRAINT FK_CUSTOMER_ID foreign key (FK_CUSTOMER_ID) references CUSTOMER (CUSTOMER_ID),
    CONSTRAINT PK_ORDER_HEADER_ID PRIMARY KEY (ORDER_HEADER_ID)
);
CREATE SEQUENCE ORDER_HEADER_SEQ START WITH 1 INCREMENT BY 1;

CREATE TABLE ORDER_DETAIL
(
    ORDER_DETAIL_ID       numeric,
    FK_ITEM_ID          numeric,
    AMOUNT              numeric,
    SHIPPING_DATE       timestamp,
    PRICE_OF_ORDER_DETAIL numeric,
    FK_ORDER_HEADER_ID         numeric,
    CONSTRAINT PK_ORDER_DETAIL_ID PRIMARY KEY (ORDER_DETAIL_ID),
    CONSTRAINT FK_ITEM_ID foreign key (FK_ITEM_ID) references ITEM (ITEM_ID),
    CONSTRAINT FK_ORDER_HEADER_ID foreign key (FK_ORDER_HEADER_ID) references ORDER_HEADER (ORDER_HEADER_ID)
);
CREATE SEQUENCE ORDER_DETAIL_SEQ START WITH 1 INCREMENT BY 1;

INSERT INTO ORDER_HEADER (ORDER_HEADER_ID, FK_CUSTOMER_ID, TOTAL_PRICE) VALUES (nextVal('order_header_seq'), 1,0);